name: measure-uid
channels:
  - defaults
  - conda-forge
  - pytorch
  - r
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scikit-learn
  - nltk
  - tqdm
  - notebook
  - matplotlib
  - pylint=2.4.4
  - pip
  - pip:
    - seaborn
    - ipdb
    - rpy2
    - tzlocal
    - simplegeneric
    - transformers
    - https://github.com/kpu/kenlm/archive/master.zip
